### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by nathanaelhuh** [enochtsang/TerminalFighter#112]
The game crashes and displays 
```
intel_do_flush_locked failed: Cannot allocate memory
[Thread 0x7ffff5393700 (LWP 2733) exited]
[Thread 0x7ffff7fcae80 (LWP 2727) exited]
[Inferior 1 (process 2727) exited with code 01]
``` 
and when using gdb and backtrace, I get
 ```
No stack.
```
Running using gdb gives the same error as running normally

![free -h 2](https://user-images.githubusercontent.com/19790536/33594152-f8ca9bfc-d94f-11e7-995d-85b2e69209d2.png)
This is a screenshot of when I do free -h

![unnamed 2](https://user-images.githubusercontent.com/19790536/33594163-0683386c-d950-11e7-9479-0a70474ccc6e.png)
This is a screenshot of my System Activity. The drop in the ram is when the game crashed. 

![linux system information](https://user-images.githubusercontent.com/19790536/33594227-4f16a8ca-d950-11e7-8f8c-a5a671fc4375.png)
This is a screenshot of my computer hardware details.

I also ran the program using tee and this is the output
[output.txt](https://github.com/JeLLyNinjas/TerminalFighter/files/1529989/output.txt)

**Comment by bseto** [comment]
Closing as this applied to the c++ version
