### ISSUE TITLE
Terminal: when typing Ctrl+(character) causes ? with box 

### ISSUE THREAD

**Issue by gordon-cheung** [enochtsang/TerminalFighter#12]
![screenshot from 2015-09-22 22 37 11](https://cloud.githubusercontent.com/assets/14229195/10037956/9461c824-617a-11e5-9a81-9ada9870a18f.png)

If you press ctrl + a,b,c,d,.... you get a ? surrounded by a box, see uploaded image

**Comment by ExtraGravity** [comment]
I can fix this
