### ISSUE TITLE
New Enemy

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#17]
So for the prototype, it'd be good to showcase that different weapons are more effective against different enemies. I was thinking adding one more enemy that strafes around, making it very difficult for the rifle to hit it. On the other hand, the homing missiles will have no problem tracking them down. The downside is that either, the homing missiles don't do enough damage to the basic grunts, or the homing missiles take longer to type. Here's a more organized explanation:

Rifle - Effective against basic grunts due to being easy to type and always hitting, ineffective to strafing fighters due to frequently missing

Homing Missiles - Effective against strafing fighters due to always hitting them, ineffective to basic grunts due to taking a long time to type. The game master will spawn them in groups of 2-5 to make it more enticing to use the homing missiles.

**Comment by bseto** [comment]
A question then. The homing missile will hit only what it collides with right? So the strategy would be to get rid of the other stuff first before using the homing? Also, will the homing **missile** explode and cause splash damage?

**Comment by ExtraGravity** [comment]
I think that leaves it as optional whether to clear other things first, we'll have to see how it plays once it's all implemented but I don't think that needs to be a requirement.

For simplicity in the prototype, it will not explode. I think it'd be good to implement explosions later.
