### ISSUE TITLE
New Names

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#18]
The names right now are extraordinarily lame, here's my suggestions for some new ones.

Rifle -> R22 .33 Rifle
Homing Missiles -> M5 Tracking Helldarts
Basic Grunt -> FKL Fighter (You can guess what FK L stands for hahaha)
Strafing Fighter -> SOS Fighter (Slightly Organized Squadron Fighter)

**Comment by gordon-cheung** [comment]
Rifle --> R9 .33 AP Cannon-I     (AP stands for Armour-Piercing)

**Comment by cheunggg** [comment]
Rifle --> R9 .33 AP Cannon-I

**Comment by ExtraGravity** [comment]
Rifle --> R9 .33 Cannon - I (no armor piercing)

**Comment by bseto** [comment]
ENCM 511 --> Troll Item that inserts spelling mistakes on the enemies if used.
