### ISSUE TITLE
Failure Indication

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#22]
There should be an indication of failure somewhere when the user presses enter but does not type any target tag. Suggestions as to what this indication should be?

I say the terminal should flash, another other ideas? @bseto @cheunggg @beaesguerra @zacharykoo

**Comment by bseto** [comment]
I think the flashing would be kind of confusing. We could just have nothing happen or maybe a "Spark" fly out of the ship that just disintegrates.

**Comment by ExtraGravity** [comment]
I disagree with nothing happening. I like the idea of a misfire though
