### ISSUE TITLE
Window Size Compatability

### ISSUE THREAD

**Issue by gordon-cheung** [enochtsang/TerminalFighter#3]
Current window size is too large.

We should make options to adjust the window size so it is compatible (game window size actually fits) with the computer's resolution.

**Comment by ExtraGravity** [comment]
This guy has a decent answer, but it isn't easy to implement. 
http://gamedev.stackexchange.com/questions/18534/what-should-i-keep-in-mind-when-making-2d-games-for-multiple-resolutions

**Comment by ExtraGravity** [comment]
Fixed using DRAWING_SCALE parameter in draw functions
