### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#4]
One of the goals in this game is to give a feel that you are controlling your ship through a terminal. There's also supposed to be a radar to view the entire screen. This kind of gives two large focus areas which will be difficult to fit on one screen. I am struggling with imagining a UI that will be able to accomplish both these goals, we need a solution because I don't have one.

**Comment by ExtraGravity** [comment]
We've decided to have a larger terminal at the bottom right, with a see through history. On the bottom left, there is a screen to show whatever info we selected.

@beaesguerra @bseto @cheunggg This is what we decided right?

**Comment by beaesguerra** [comment]
Yes, that's what we decided!
