### ISSUE TITLE
Selecting Quit from main.py

### ISSUE THREAD

**Issue by beaesguerra** [enochtsang/TerminalFighter#42]
Game closes properly, but I get this error: 

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    gamestate = run_game_state.get(gamestate, sys.exit)(screen, DRAWING_SCALE)
TypeError: exit expected at most 1 arguments, got 2

**Comment by ExtraGravity** [comment]
Yea, I saw that. Not sure how to fix it, it's a fairly non issue thing right now though.

**Comment by bseto** [comment]
This is a result of not properly closing pygame. 

Example: In SDL2, I have to call:

```
void close()
{
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    window = NULL;
    renderer = NULL;
    SDL_Quit();
    exit(0);
}
```

Try to call https://www.pygame.org/docs/ref/pygame.html#pygame.quit before exit?

**Comment by ExtraGravity** [comment]
No, the problem is in the dict I use for moving between game states. Game states are a function that takes 2 arguments. `sys.exit()` takes either 0 or 1 argument.

**Comment by bseto** [comment]
ohh i see

**Comment by ExtraGravity** [comment]
Not sure if you guys want to do something about that

**Comment by bseto** [comment]
Nah, I think if you don't think its worth the effort its okay

**Comment by ExtraGravity** [comment]
I fixed the previous issues.
