### ISSUE TITLE
Enemies on main menu

### ISSUE THREAD

**Issue by beaesguerra** [enochtsang/TerminalFighter#44]
I was thinking that to play and quit, it might be a good idea to have the player actually type 'play' and 'quit' instead of random words. It would match the UI idea we had for typing certain things to view the stats, etc.

**Comment by ExtraGravity** [comment]
@bseto

**Comment by bseto** [comment]
Oh, but it wouldn't shoot the big "Play" or "Quit" words anymore right?

**Comment by beaesguerra** [comment]
It could! I liked the idea of having the enemies to shoot in the main menu, I just thought maybe we could have more relevant words to target (like start and quit) rather than having randomly selected words

**Comment by bseto** [comment]
I think that would work. we could change the words for the main menu.

**Comment by ExtraGravity** [comment]
This I think will be obsolete in the new version. Closing for now
