### ISSUE TITLE
Boss system/new weapon and story line 

### ISSUE THREAD

**Issue by zacharykoo** [enochtsang/TerminalFighter#47]
Ideas:
Boss battle every 10 waves? Where player need to type lots of harder words to damage boss, and boss can spawn small enemies or shoot slow missile that can be destroyed by player’s weapons. After defecting boss battle, player can get a new weapon.

Storyline? Like fire emblem where story and gameplay won’t be affecting each other too much, but still connected.

**Comment by ExtraGravity** [comment]
Each of these things, boss system, new weapon, and story line deserve their own issues. I'll reopen them as that.
