### ISSUE TITLE
Boss system

### ISSUE THREAD

**Issue by zacharykoo** [enochtsang/TerminalFighter#49]
Including a Boss battle every 10 waves? Where player need to type lots of harder words to damage boss, and boss can spawn small enemies or shoot slow missile that can be destroyed by player’s weapons.

**Comment by ExtraGravity** [comment]
The weapons are totally doable, but I think it's too early to talk about specifics for what bosses will do. I think for bosses, they should be at the end of levels rather than after 10 waves or etc.

**Comment by bseto** [comment]
I think it would be cool to have a boss level every 5 waves, and then every 10th wave would be a hard wave + hard boss?

Every wave for a boss would make the bosses less interesting, conversely, every 10 waves I think is not frequent enough.

**Comment by zacharykoo** [comment]
I am also thinking about the idea where you get new weapon upon bosses u defeat, thats why I am thinking 10 wave bosses

**Comment by ExtraGravity** [comment]
But the idea of waves is kind of in line with a continouous onslaught.  But I thought we would be going with a level system rather than a continuous game. I like the level system because it gives us better opportunity to give story etc.

If it's level based, then there would be some boss stages, and completing certain levels would unlock new weapons.

**Comment by beaesguerra** [comment]
I think it would be good to have levels that aren't too long and then have boss stages every 5 levels. I also think having levels makes the game less tiring because it allows you to take breaks in between

**Comment by ExtraGravity** [comment]
I was feeling that it was rather "missions" compared to levels. That way we can fine tune each "mission" to what would suit the story. Compared to sticking in a boss fight to every level.

**Comment by zacharykoo** [comment]
If we are doing a storyline, I think mission is a better idea too, and when finish certain mission, player will get new "upgrades" rather its new weapon or new ships/systems, and bosses will be more fitting at the end of the mission rather than being "randomly" appear.

**Comment by bseto** [comment]
I agree with this "mission" type gameplay. I think it'd be better than levels.

**Comment by ExtraGravity** [comment]
This seems agreed up on then. Specifics about bosses are too early to say, but all that's been suggested is totally doable. But we will have "missions" instead of "levels" and there will be boss missions.
