### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by ExtraGravity** [enochtsang/TerminalFighter#61]
In the Design Doc, the UI should be drawn as reference for whoever is implementing it.

The UI in game will be the enemy is bottom centered, a terminal bar for typing will be on the bottom right. Above it will be a semi-transparent history of typed commands. There should be a semi transparent area on the bottom left that the user can select what appears, some differnet things could be ammo left, ship health, radar, etc... I was also thinking there would be alerts that appear in the middle of the screen, so if a ship part gets destroyed an alert will appear in the middle of the screen.

**Comment by bseto** [comment]
Closing as this applied to the c++ version
