### ISSUE TITLE
Graphics Handler::Layer Levels - Needs to be done before we do graphics

### ISSUE THREAD

**Issue by bseto** [enochtsang/TerminalFighter#70]
We need to add some sort of variable to the Graphics Handler so that it knows what graphics elements should be rendered over other things. 

Should we add like a "z" component? z=0 at the rear, and the higher z values would stay above the other stuff? 

@cheunggg @beaesguerra

**Comment by ExtraGravity** [comment]
I think having any z level would get pretty hairy pretty fast. I think an enum stating the priority would be better. It would be less flexible but alot cleaner. 

ex.

``` c++
enum GraphicPriority {
    FRONT_IMPORTANT,
    UI,
    FRONT,
    MIDDLE,
    BACK,
    BACKGROUND
}
```

In this example, normal game objects have 3 different layers to play with, `FRONT`, `MIDDLE`, and `BACK`. Then we have the  `UI` layer for ui stuff, `FRONT_IMPORTANT` for maybe some cool effects, then `BACKGROUND` for background.

**Comment by bseto** [comment]
Ya, I think this would work too. We could always add more enums if we needed it.

**Comment by ExtraGravity** [comment]
Fixed
